name = "Matcha Plus"
author = "Fayranchia"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ee683ca5ac95baea43200bf8a00f12a09c98e4a78719f7b22802d31b9afc4e3"

[versions]
minecraft = "26.2"
quilt = "0.30.1-beta.2"

[options]
datapack-folder = "resources/datapack/required/"
