name = "Matcha Plus"
author = "Fayranchia"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "009c6b628afc3ce896f465d81d73cb7c9160533d45037613083eb82060ea7d25"

[versions]
minecraft = "26.2"
quilt = "0.30.1-beta.2"

[options]
datapack-folder = "resources/datapack/required/"
