name = "Matcha Plus"
author = "Fayranchia"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "379c8b30c2af6cc98446bb181440ee17643872c6bcbb2b5d1c2700edbd451d78"

[versions]
minecraft = "26.2"
quilt = "0.30.1-beta.2"

[options]
datapack-folder = "resources/datapack/required/"
